>> programmers 파이썬 입문 강의를 학습, 정리한 내용입니다 (https://programmers.co.kr/learn/courses/2)

# 12. 예외처리

- [12. 예외처리](#12-예외처리)
- [try except](#try-except)
  - [index error](#index-error)
  - [value errer](#value-errer)
  - [try-except 문](#try-except-문)
    - [try-except vs if-else](#try-except-vs-if-else)
  - [실습 `try_except.py`](#실습-try_exceptpy)
    - [결과](#결과)
  - [try except 요점정리](#try-except-요점정리)
    - [예외 처리](#예외-처리)
- [예외의 이름을 모를 때](#예외의-이름을-모를-때)
  - [실습 `except.py`](#실습-exceptpy)
    - [결과](#결과-1)
  - [예외의 이름을 모를 때 요점정리](#예외의-이름을-모를-때-요점정리)
    - [예외 이름을 모르는 경우 처리 방법](#예외-이름을-모르는-경우-처리-방법)
- [raise](#raise)
  - [ValueError](#valueerror)
  - [StopIteration](#stopiteration)
  - [실습 `raise.py`](#실습-raisepy)
  - [raise 요점정리](#raise-요점정리)
    - [예외 발생](#예외-발생)

<small><i><a href='http://ecotrust-canada.github.io/markdown-toc/'>Table of contents generated with markdown-toc</a></i></small>


# try except
프로그래밍을 하다 보면 에러가 나기도 한다.
이러한 에러는 반드시 피하기만 해야 할 것이 아니라 프로그래밍에 도움이 되는 도구가 되기도 한다.
## index error
빈 리스트의 요소를 불러오면 발생
```powershell
>>> list = []
>>> list[0]
Traceback (most recent call last):   
  File "<stdin>", line 1, in <module>
IndexError: list index out of range  
```
## value errer
유효하지 않은 리터럴
```powershell
>>> text = 'abc'
>>> number = int(text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'abc'
```
## try-except 문
* 에러가 발생할 가능성이 있는 코드를 try아래에 에러 발생시 실행할 코드를 except아래에 작성해 별도로 처리 할 수 있다.
* if 조건문을 사용해 예외처리 코드를 작성할 수 있다.
### try-except vs if-else
  * try-except문과 if문 중에 선택할 수 있다면 코드가 간결하고 쉬워지는 쪽을 선택
  * 잘 모르겠다면 쉽게 생각나는 쪽을 선택
  * 양쪽이 비슷하다면 if문을 사용하는 것이 좋다
  * 어떤 문제는 try-except가 아니면 거의 해결하기 어려운 것도 있다.

## 실습 `try_except.py`
```py
# case1 :
# try-except문 예시
text = '100%'
try:
    number = int(text)
except ValueError:
    print('{}는 숫자가 아니네요.'.format(text))

# case2 :
# try-except문으로 예외처리하기
def safe_pop_print(list, index):
    try:
        print(list.pop(index))
    except IndexError:
        print('{} index의 값을 가져올 수 없습니다.'.format(index))

safe_pop_print([1,2,3],5)

# if문으로 예외처리하기
def safe_pop_print(list, index):
    if index<len(list):
        print(list.pop(index))
    else:
        print('{} index의 값을 가져올 수 없습니다.'.format(index))

safe_pop_print([1,2,3],5)

# case3 :
# try-except문만 가능
try:
    import my1_module
except ImportError:
    print("모듈이 없습니다.")
```
### 결과
```
100%는 숫자가 아니네요.
5 index의 값을 가져올 수 없습니다.
5 index의 값을 가져올 수 없습니다.
모듈이 없습니다.
```

## try except 요점정리
### 예외 처리
```py
try:
    # 에러가 발생할 가능성이 있는 코드
except Exception: # 에러 종류
    #에러가 발생 했을 경우 처리할 코드
```
* 경우에 따라 예외 처리 대신 if else를 사용 할 수 있다.


# 예외의 이름을 모를 때

## 실습 `except.py`
```py
# case1:
try:
    list = []
    print(list[0])
except Exception as ex:
    print('에러가 발생했습니다.',ex)
# case2:
try:
    text = 'abc'
    number = int(text)
except Exception as ex:
    print('에러가 발생했습니다.',ex)
```
### 결과
```
에러가 발생했습니다. list index out of range
에러가 발생했습니다. invalid literal for int() with base 10: 'abc'
```

## 예외의 이름을 모를 때 요점정리
### 예외 이름을 모르는 경우 처리 방법
```py
try:
    # 에러가 발생할 가능성이 있는 코드
except Exception as ex: # 에러 종류
    print('에러가 발생 했습니다', ex) # ex는 발생한 에러의 이름을 받아오는 변수
```


# raise
에러를 직접 일으키는 방법을 알아보자
* 예를 들어 잘못된 값을 넣은 경우 `raise`를 사용해 직접 에러를 발생시킬 수 있다.
> [python-docs-errors](https://docs.python.org/ko/3/tutorial/errors.html)
## ValueError
* 올바른 타입이지만 부적절한 값을 가진 인자를 연산이나 함수가 받았고, 상황이 `IndexError` 처럼 더 구체적인 예외로 설명되지 않는 경우 발생
## StopIteration
* 내장 함수 `next()`와 `iterator`의 `__next__()` 메서드가 `iterator`에 의해 생성된 항목이 더 없다는 것을 알려주기 위해 발생시킴
## 실습 `raise.py`
```py
# case1: 
def rsp(mine,yours):
    #가위바위보 승패를 판단하는 코드
    allowed = ['가위', '바위', '보']
    if mine not in allowed:
        raise ValueError
    if yours not in allowed:
        raise ValueError

try:
    rsp('가위', '바')
except ValueError:
    print('잘못된 값을 넣은 것 같습니다.')

# case2:
school = {'1반': [172,185,198,177,165,199], '2반':[165,177,167,180,191]}
# 190넘는 학생이 있으면 반 이름 출력 후 즉시 종료
for class_number, students in school.items():
    for student in students:
        if student>190:
            print(class_number, '에 190을 넘는 학생이 있습니다.')
            break # for문 하나만 종료
            
# 중첩된 for문에서 바로 종료 - `raise StopIteration`
school = {'1반': [172,185,198,177,165,199], '2반':[165,177,167,180,191]}
try:
    for class_number, students in school.items():
        for student in students:
            if student>190:
                print(class_number, '에 190을 넘는 학생이 있습니다.')
                raise StopIteration
except StopIteration:
    print('정상 종료')
```
```powershell
# case1
잘못된 값을 넣은 것 같습니다.
# case2
1반 에 190을 넘는 학생이 있습니다.
2반 에 190을 넘는 학생이 있습니다.
# case2-2
1반 에 190을 넘는 학생이 있습니다.
정상 종료
```
## raise 요점정리
### 예외 발생
* 사용자가 직접 에러를 발생시키는 기능
* raise Exception # 에러 종류
* 많이 사용하면 코드를 읽기 어려워진다.